name: Build and Test Suite

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  packages: none

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libxapian-dev libxapian30
    - name: checkout
      uses: actions/checkout@v3
    - name: configure rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        override: true
        toolchain: stable
        components: clippy
    - name: configure build cache
      uses: actions/cache@v3
      with:
        key: cargo-${{ hashFiles('**/Cargo.lock') }}-ci
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        toolchain: stable
        command: build
        args:
          --all-targets
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        toolchain: stable
    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        toolchain: stable
